### ISSUE TITLE
1.2一直卡在目前检测游戏列表

### ISSUE THREAD

**Issue by LeticiaAnna** [6yy66yy/legod-auto-pause#1]
1.2一直卡在目前检测游戏列表 这该如何处理呢 WIN10 企业版最新

**Comment by 6yy66yy** [comment]
看一下Wiki中 [新手上路](https://github.com/6yy66yy/legod-auto-pause/wiki/%E6%96%B0%E6%89%8B%E4%B8%8A%E8%B7%AF)部分，正确设置后，不开游戏就会处于`开始检测`，当打开列表中的游戏后，就会显示`检测到xxx`

**Comment by millionart** [comment]
完全没有效果，我都是先开这个工具，通过工具启动雷神，加速后再启动游戏，玩完后退出游戏，等半天还是检测到XX游戏，进程里早就没有相关内容了。
这个工具用了有2年了，没有一次正常帮我停止过雷神，从2.2.1到现在2.2.3
我现在打字的时候旁边就放着这个工具和雷神，游戏早就退了，根本不生效
