### ISSUE TITLE
神奇的事情

### ISSUE THREAD

**Issue by int0828** [6yy66yy/legod-auto-pause#14]
我打war thunder 发现确实是可以 关闭时间的 但是war thunder加速没停 刷新了也不停
![image](https://github.com/6yy66yy/legod-auto-pause/assets/65404866/c0f098b3-5fbf-418e-930e-d9f32c37f0ad)

**Comment by fgr178707** [comment]
> 我打war thunder 发现确实是可以 关闭时间的 但是war thunder加速没停 刷新了也不停 ![image](https://private-user-images.githubusercontent.com/65404866/271918170-c0f098b3-5fbf-418e-930e-d9f32c37f0ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzM2NzksIm5iZiI6MTcwMjQzMzM3OSwicGF0aCI6Ii82NTQwNDg2Ni8yNzE5MTgxNzAtYzBmMDk4YjMtNWZiZi00MThlLTkzMGUtZDlmMzJjMzdmMGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDAyMDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2MTljNzMzYjQ3NGVjMDg0M2ExNTVlYzFiYmI1YmFmZjVmZTEwODU3NjZhMGFkOTk4OGI4ZjAxZjk2ZjJhMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6yH8NhMZdaFuHRJ2kvz9kKJVqmkBb3dpzY_sRdtJSYE)

这个问题是属于雷神的问题 你不用管 只要时长暂停了就可以

**Comment by 6yy66yy** [comment]
已添加至Wiki说明 [wiki](https://github.com/6yy66yy/legod-auto-pause/wiki/%E4%B8%80%E4%BA%9B%E5%B8%B8%E8%A7%81%E7%96%91%E9%97%AE%E5%8F%8A%E8%A7%A3%E7%AD%94%EF%BC%88AI%E7%94%9F%E6%88%90%EF%BC%89#%E7%A8%8B%E5%BA%8F%E6%8F%90%E7%A4%BA%E6%97%B6%E9%97%B4%E6%9A%82%E5%81%9C%E4%BA%86%E4%BD%86%E6%98%AF-%E5%8A%A0%E9%80%9F%E5%AE%A2%E6%88%B7%E7%AB%AF%E8%AE%A1%E6%97%B6-%E6%B2%A1%E6%9C%89%E5%81%9C%E6%AD%A2)
