### ISSUE TITLE
无法运行程序，开启时报错[BUG🐛]

### ISSUE THREAD

**Issue by MongoYL** [6yy66yy/legod-auto-pause#15]
Failed to execute script 'Traylcon' due to unhandled
exception: 'legod' object has no attribute 'applist'
Traceback (most recent call last):
File "Traylcon.py", line 222, in <module>
File "Traylcon.py", line 77, in init
AttributeError: 'legod' object has no attribute 'applist'

**Comment by aW3ikun** [comment]
没法复现。
详细操作麻烦讲一下。

**Comment by aW3ikun** [comment]
> Failed to execute script 'Traylcon' due to unhandled exception: 'legod' object has no attribute 'applist' Traceback (most recent call last): File "Traylcon.py", line 222, in File "Traylcon.py", line 77, in init AttributeError: 'legod' object has no attribute 'applist'

没法复现。
详细操作麻烦讲一下。

**Comment by lc09cn** [comment]
so am i
