### ISSUE TITLE
[增强👾]启动程序的使用自动启动加速器

### ISSUE THREAD

**Issue by WuJvya** [6yy66yy/legod-auto-pause#16]
**您的功能请求是否与问题有关？请描述。**

**描述一下你希望有的新功能**
【可不可以添加关机暂停加速的功能（提前回复：不行）】

**描述一下你的备选方案**
【可不可以添加暂停加速直接关机的功能（提前回复：可以x）】

**Additional context**

**Comment by 6yy66yy** [comment]
**程序不会操作加速器本体，使用方式仅限于手动开启加速、关闭游戏脚本自动暂停**
新增游戏关闭时弹出一个是否关闭加速的弹窗的功能。
https://github.com/6yy66yy/legod-auto-pause/releases/tag/v2.2.1-beta
