### ISSUE TITLE
[BUG🐛]已解决，加上MD5 = 0

### ISSUE THREAD

**Issue by lc09cn** [6yy66yy/legod-auto-pause#17]
**描述一下你遇到的问题**
启动报错

**遇到问题前你做了什么**
按步骤描述你做了什么:
1.解压至文件夹  
2.运行

**应有的行为**

**截图（如有）**
非命令行版本
Traceback (most recent call last):
  File "TrayIcon.py", line 222, in <module>
  File "TrayIcon.py", line 77, in __init__
AttributeError: 'legod' object has no attribute 'applist'

命令行版本
Traceback (most recent call last):
  File "legod.py", line 300, in <module>
  File "legod.py", line 276, in detection
  File "legod.py", line 136, in check_exsit
AttributeError: 'legod' object has no attribute 'applist'
[26412] Failed to execute script 'legod' due to unhandled exception!
**描述你的平台（尽可能详尽）**
 - 系统：windows11 
 - 程序版本：2.2.1

**补充**
2.2正常，运行2.2.1有退出2.2
xxx/legod-auto-pause  (2.2.1路径)
xxx/legod-auto-pausev2.2-CommandLine  (2.2路径)

**Comment by lc09cn** [comment]
https://github.com/6yy66yy/legod-auto-pause/issues/15
同样故障，然后管理员模式也不行

**Comment by 6yy66yy** [comment]
检查配置文件中的条目是否与原本包中的一致

**Comment by aW3ikun** [comment]
> **描述一下你遇到的问题** 启动报错
> 
> **遇到问题前你做了什么** 按步骤描述你做了什么: 1.解压至文件夹 2.运行
> 
> **应有的行为**
> 
> **截图（如有）** 非命令行版本 Traceback (most recent call last): File "TrayIcon.py", line 222, in File "TrayIcon.py", line 77, in **init** AttributeError: 'legod' object has no attribute 'applist'
> 
> 命令行版本 Traceback (most recent call last): File "legod.py", line 300, in File "legod.py", line 276, in detection File "legod.py", line 136, in check_exsit AttributeError: 'legod' object has no attribute 'applist' [26412] Failed to execute script 'legod' due to unhandled exception! **描述你的平台（尽可能详尽）**
> 
> * 系统：windows11
> * 程序版本：2.2.1
> 
> **补充** 2.2正常，运行2.2.1有退出2.2 xxx/legod-auto-pause (2.2.1路径) xxx/legod-auto-pausev2.2-CommandLine (2.2路径)

默认配置文件能够运行吗？ 能否看看配置文件？ or 你录个视频

**Comment by lc09cn** [comment]
> 检查配置文件中的条目是否与原本包中的一致
[config]
path = "C:\Program Files (x86)\LeiGod_Acc\leigod.exe"
uname = 186xxx
password = xxx
games = cs2
looptime = 30
update = 10
account_token = xxx

**Comment by lc09cn** [comment]
> 检查配置文件中的条目是否与原本包中的一致
少了MD5这个，加上就OK
