### ISSUE TITLE
[增强👾]开机自启动

### ISSUE THREAD

**Issue by lc09cn** [6yy66yy/legod-auto-pause#18]
**您的功能请求是否与问题有关？请描述。**

**描述一下你希望有的新功能**
【可不可以添加关机暂停加速的功能（提前回复：不行）】

**描述一下你的备选方案**
【可不可以添加暂停加速直接关机的功能（提前回复：可以x）】

**Additional context**

目前用批处理实现，能否程序原生
@echo off
d:
cd D:\Display\Tools\legod-auto-pause
start legodpause.exe
taskkill /f /im cmd.exe
exit

**Comment by 6yy66yy** [comment]
不准备在程序中内嵌，如有需要请查看：
[如何设置开机自启](https://github.com/6yy66yy/legod-auto-pause/wiki/%E4%B8%80%E4%BA%9B%E5%B8%B8%E8%A7%81%E7%96%91%E9%97%AE%E5%8F%8A%E8%A7%A3%E7%AD%94%EF%BC%88AI%E7%94%9F%E6%88%90%EF%BC%89#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
