### ISSUE TITLE
缺少依赖还是运行环境？

### ISSUE THREAD

**Issue by DongGua-Jun** [6yy66yy/legod-auto-pause#2]
![image](https://user-images.githubusercontent.com/75875483/189517402-831b65f7-6232-470f-8daa-d07c91012695.png)
已经装了py3.8

![image](https://user-images.githubusercontent.com/75875483/189517426-183e8a3d-4826-4494-9839-5f665470bbd7.png)

报错提示的chardet和ur库也装了

暂停通知弹出来但实际没有成功暂停

**Comment by 6yy66yy** [comment]
不是依赖的问题，这里用的是我编译时这两个包版本冲突，对于使用无影响
一般来说这样才是成功，你可能是进程名设置错误，未检测到游戏
![image](https://user-images.githubusercontent.com/44695760/189517786-00292787-3746-4c1f-b91e-701857a8f278.png)

**Comment by 6yy66yy** [comment]
已更新版本库重新打包
尝试下载新版本
