### ISSUE TITLE
[BUG🐛] 登陆链接好像变了，你能帮忙改一下不。我手上暂时没环境。

### ISSUE THREAD

**Issue by JA1E0** [6yy66yy/legod-auto-pause#21]
**描述一下你遇到的问题**
登陆链接被改变，需要测试

<img width="787" alt="image" src="https://github.com/user-attachments/assets/140a7a05-e22f-4b53-bdd7-22a4ce1e92f7">

按步骤描述你做了什么:
https://webapi.leigod.com/api/auth/login/v1

**Comment by 6yy66yy** [comment]
ok, 我这两天看下

**Comment by 6yy66yy** [comment]
看了一下，貌似请求报文都变了，添加了签名。貌似得扒一下js代码了，有点麻烦。
```python 

{
    "os_type":4, # 系统类型
    "password":"", # md5密码 没变
    "mobile_num":"", # 手机号
    "src_channel":"guanwang",
    "country_code":86,
    "username":"", # 用户名，貌似也是手机号
    "lang":"zh_CN",
    "region_code":1, # 不太懂，貌似不用管
    "account_token":null, # 大概是旧的token
    "ts":"1723456516", # 以秒为单位的时间戳
    "sign":"2e2b3264727a19550a160717e58dace0" # 签名值
}
```

**Comment by JA1E0** [comment]
> ```python
> 2e2b3264727a19550a160717e58dace0
> ```

函数在index.js?3ab173e773704f3daf42 文件内。 有个`URL_AUTH_LOGIN_V1: "/api/auth/login/v1",`

**Comment by JA1E0** [comment]
这是sign函数的位置index.js里面。 <img width="473" alt="image" src="https://github.com/user-attachments/assets/51493e4c-e428-4170-b473-7af9a11c1c80">

**Comment by 6yy66yy** [comment]
已修复

**Comment by luanche** [comment]
分享用chatgpt分析出来签名函数的流程，感受到了ai的强大
https://chatgpt.com/share/6710aa42-6acc-8010-8772-699915730f0d
