### ISSUE TITLE
[BUG🐛]暂停功能好像失效了

### ISSUE THREAD

**Issue by s1sunny** [6yy66yy/legod-auto-pause#22]
BUG反馈，感谢互联网活菩萨！

**Comment by Yia-wooh** [comment]
我现在也不能自动暂停了，弹窗会提示未知错误

**Comment by 6yy66yy** [comment]
已修复：[releases-v2.2.3](https://github.com/6yy66yy/legod-auto-pause/releases/tag/v2.2.3)
