### ISSUE TITLE
[BUG🐛]好像把登录接口关了 登录不上

### ISSUE THREAD

**Issue by jsdfhasuh** [6yy66yy/legod-auto-pause#27]
请求这个地址https://webapi.leigod.com/api/auth/login/v1

b'<!DOCTYPE html><html style="height:100%;width:100%"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta http-equiv="Server" content="CloudWAF" /><title id="title">\xe8\xae\xbf\xe9\x97\xae\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa\xef\xbc\x81</title></head><body onload="bindall()" style="height:100%;width:100%;margin:0px;font-family:Microsoft yahei"><div><style type="text/css">\t.select {float: right;margin: 10px 20px 0 0;height: 32px;line-height: 20px;font-size: 14px;width: 80px;}</style><select class="select" name="language" onchange="changeLanguage(this.options[this.options.selectedIndex].value)"><option id="option-zh" onclick="changeLanguageZh()" value="zh">\xe4\xb8\xad\xe6\x96\x87</option><option id="option-en" onclick="changeLanguageEn()" value="en">English</option></select><div style="clear: both;"></div></div><div style="min-height:13.125rem;width:100%"><div style="margin-top:3.75rem;margin-left:18.4375rem;height:52.38;width:83.04%;"><svg xmlns="http://www.w3.org/2000/svg" style="width: 3.125rem;height: 3.125rem" viewBox="0 0 50 50"><path fill="#e84e4c" d="M25,0A25,25,0,1,0,50,25,25,25,0,0,0,25,0Zm1.6,37.16H22.85V33.41H26.6Zm0-6.63H22.85L22.35,13H27.1Z"/></svg><font style="font-family:MicrosoftYaHei;font-size:4.375rem;color:#e94d4c;margin-left: 0.75rem;font-weight: bold;">418</font></div><div style="margin-left:18.4375rem;height:47.62%;width:83.04%;"><font id="a" style="font-family:MicrosoftYaHei;font-size:1.875rem;color:#999999;word-wrap:break-word;">\xe6\x82\xa8\xe7\x9a\x84\xe8\xaf\xb7\xe6\xb1\x82\xe7\x96\x91\xe4\xbc\xbc\xe6\x94\xbb\xe5\x87\xbb\xe8\xa1\x8c\xe4\xb8\xba\xef\xbc\x81</font><p style="font-family:MicrosoftYaHei;font-size:0.9rem;color:#999999;word-wrap:break-word;"><span id="c">\xe4\xba\x8b\xe4\xbb\xb6ID\xef\xbc\x9a</span><span style="color:#499df2" id="d">30-dect-149-20241130100648-e55375d8</span></p></div></div><div style="height:15.625rem;width:100%;min-width:105rem;"><div style="margin-left:18.4375rem;float:left;width:50rem"><p id="b" style="margin-top:10px">\xe5\xa6\x82\xe6\x9e\x9c\xe6\x82\xa8\xe6\x98\xaf\xe7\xab\x99\xe9\x95\xbf\xef\xbc\x8c\xe6\x82\xa8\xe5\x8f\xaf\xe4\xbb\xa5\xe5\x89\x8d\xe5\xbe\x80WAF\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xbf\x9b\xe8\xa1\x8c\xe8\xaf\xaf\xe6\x8a\xa5\xe5\xb1\x8f\xe8\x94\xbd\xe8\xae\xbe\xe7\xbd\xae\xef\xbc\x8c\xe8\xae\xa9\xe6\x82\xa8\xe7\x9a\x84\xe8\xae\xbf\xe9\x97\xae\xe4\xb8\x8d\xe5\x86\x8d\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa</p></div></div></body><script>function changeLanguage(value) {if (value === \'zh\') {changeLanguageZh();} else if (value === \'en\') {changeLanguageEn();} else {changeLanguageZh();}}function changeLanguageZh() {document.getElementById("title").innerHTML = "\xe8\xae\xbf\xe9\x97\xae\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa\xef\xbc\x81";document.getElementById("a").innerHTML = "\xe6\x82\xa8\xe7\x9a\x84\xe8\xaf\xb7\xe6\xb1\x82\xe7\x96\x91\xe4\xbc\xbc\xe6\x94\xbb\xe5\x87\xbb\xe8\xa1\x8c\xe4\xb8\xba\xef\xbc\x81";document.getElementById("b").innerHTML = "\xe5\xa6\x82\xe6\x9e\x9c\xe6\x82\xa8\xe6\x98\xaf\xe7\xab\x99\xe9\x95\xbf\xef\xbc\x8c\xe6\x82\xa8\xe5\x8f\xaf\xe4\xbb\xa5\xe5\x89\x8d\xe5\xbe\x80WAF\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xbf\x9b\xe8\xa1\x8c\xe8\xaf\xaf\xe6\x8a\xa5\xe5\xb1\x8f\xe8\x94\xbd\xe8\xae\xbe\xe7\xbd\xae\xef\xbc\x8c\xe8\xae\xa9\xe6\x82\xa8\xe7\x9a\x84\xe8\xae\xbf\xe9\x97\xae\xe4\xb8\x8d\xe5\x86\x8d\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa";document.getElementById("c").innerHTML = "\xe4\xba\x8b\xe4\xbb\xb6ID\xef\xbc\x9a";}function changeLanguageEn() {document.getElementById("title").innerHTML = "The access is blocked.";document.getElementById("a").innerHTML = "Sorry, your request has been intercepted because it appears to be an attack.";document.getElementById("b").innerHTML = "If you are the webmaster, configure related parameters on the WAF console to allow your requests.";document.getElementById("c").innerHTML = "Event ID:";}var language = navigator.language || navigator.browserLanguage;var re_zh = /^zh/;if (language.match(re_zh)) {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);} else {changeLanguageEn();document.getElementById("option-en").setAttribute("selected", true);}</script></html>\n'

**Comment by JA1E0** [comment]
现在官网可以登陆了，你试试软件能用了不呢？

> 请求这个地址https://webapi.leigod.com/api/auth/login/v1
> 
> b'<title id="title">\xe8\xae\xbf\xe9\x97\xae\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa\xef\xbc\x81</title>
> 
> <style type="text/css">\t.select {float: right;margin: 10px 20px 0 0;height: 32px;line-height: 20px;font-size: 14px;width: 80px;}</style>\xe4\xb8\xad\xe6\x96\x87English
> 418
> \xe6\x82\xa8\xe7\x9a\x84\xe8\xaf\xb7\xe6\xb1\x82\xe7\x96\x91\xe4\xbc\xbc\xe6\x94\xbb\xe5\x87\xbb\xe8\xa1\x8c\xe4\xb8\xba\xef\xbc\x81
> \xe4\xba\x8b\xe4\xbb\xb6ID\xef\xbc\x9a30-dect-149-20241130100648-e55375d8
> 
> \xe5\xa6\x82\xe6\x9e\x9c\xe6\x82\xa8\xe6\x98\xaf\xe7\xab\x99\xe9\x95\xbf\xef\xbc\x8c\xe6\x82\xa8\xe5\x8f\xaf\xe4\xbb\xa5\xe5\x89\x8d\xe5\xbe\x80WAF\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xbf\x9b\xe8\xa1\x8c\xe8\xaf\xaf\xe6\x8a\xa5\xe5\xb1\x8f\xe8\x94\xbd\xe8\xae\xbe\xe7\xbd\xae\xef\xbc\x8c\xe8\xae\xa9\xe6\x82\xa8\xe7\x9a\x84\xe8\xae\xbf\xe9\x97\xae\xe4\xb8\x8d\xe5\x86\x8d\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa
> 
> <script>function changeLanguage(value) {if (value === 'zh') {changeLanguageZh();} else if (value === 'en') {changeLanguageEn();} else {changeLanguageZh();}}function changeLanguageZh() {document.getElementById("title").innerHTML = "\xe8\xae\xbf\xe9\x97\xae\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa\xef\xbc\x81";document.getElementById("a").innerHTML = "\xe6\x82\xa8\xe7\x9a\x84\xe8\xaf\xb7\xe6\xb1\x82\xe7\x96\x91\xe4\xbc\xbc\xe6\x94\xbb\xe5\x87\xbb\xe8\xa1\x8c\xe4\xb8\xba\xef\xbc\x81";document.getElementById("b").innerHTML = "\xe5\xa6\x82\xe6\x9e\x9c\xe6\x82\xa8\xe6\x98\xaf\xe7\xab\x99\xe9\x95\xbf\xef\xbc\x8c\xe6\x82\xa8\xe5\x8f\xaf\xe4\xbb\xa5\xe5\x89\x8d\xe5\xbe\x80WAF\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xbf\x9b\xe8\xa1\x8c\xe8\xaf\xaf\xe6\x8a\xa5\xe5\xb1\x8f\xe8\x94\xbd\xe8\xae\xbe\xe7\xbd\xae\xef\xbc\x8c\xe8\xae\xa9\xe6\x82\xa8\xe7\x9a\x84\xe8\xae\xbf\xe9\x97\xae\xe4\xb8\x8d\xe5\x86\x8d\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa";document.getElementById("c").innerHTML = "\xe4\xba\x8b\xe4\xbb\xb6ID\xef\xbc\x9a";}function changeLanguageEn() {document.getElementById("title").innerHTML = "The access is blocked.";document.getElementById("a").innerHTML = "Sorry, your request has been intercepted because it appears to be an attack.";document.getElementById("b").innerHTML = "If you are the webmaster, configure related parameters on the WAF console to allow your requests.";document.getElementById("c").innerHTML = "Event ID:";}var language = navigator.language || navigator.browserLanguage;var re_zh = /^zh/;if (language.match(re_zh)) {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);} else {changeLanguageEn();document.getElementById("option-en").setAttribute("selected", true);}</script>\n'

**Comment by jsdfhasuh** [comment]
> 现在官网可以登陆了，你试试软件能用了不呢？
> 
> > 请求这个地址https://webapi.leigod.com/api/auth/login/v1
> > b'<title id="title">\xe8\xae\xbf\xe9\x97\xae\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa\xef\xbc\x81</title>
> > <style type="text/css">\t.select {float: right;margin: 10px 20px 0 0;height: 32px;line-height: 20px;font-size: 14px;width: 80px;}</style>\xe4\xb8\xad\xe6\x96\x87English
> > 418
> > \xe6\x82\xa8\xe7\x9a\x84\xe8\xaf\xb7\xe6\xb1\x82\xe7\x96\x91\xe4\xbc\xbc\xe6\x94\xbb\xe5\x87\xbb\xe8\xa1\x8c\xe4\xb8\xba\xef\xbc\x81
> > \xe4\xba\x8b\xe4\xbb\xb6ID\xef\xbc\x9a30-dect-149-20241130100648-e55375d8
> > \xe5\xa6\x82\xe6\x9e\x9c\xe6\x82\xa8\xe6\x98\xaf\xe7\xab\x99\xe9\x95\xbf\xef\xbc\x8c\xe6\x82\xa8\xe5\x8f\xaf\xe4\xbb\xa5\xe5\x89\x8d\xe5\xbe\x80WAF\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xbf\x9b\xe8\xa1\x8c\xe8\xaf\xaf\xe6\x8a\xa5\xe5\xb1\x8f\xe8\x94\xbd\xe8\xae\xbe\xe7\xbd\xae\xef\xbc\x8c\xe8\xae\xa9\xe6\x82\xa8\xe7\x9a\x84\xe8\xae\xbf\xe9\x97\xae\xe4\xb8\x8d\xe5\x86\x8d\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa
> > <script>function changeLanguage(value) {if (value === 'zh') {changeLanguageZh();} else if (value === 'en') {changeLanguageEn();} else {changeLanguageZh();}}function changeLanguageZh() {document.getElementById("title").innerHTML = "\xe8\xae\xbf\xe9\x97\xae\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa\xef\xbc\x81";document.getElementById("a").innerHTML = "\xe6\x82\xa8\xe7\x9a\x84\xe8\xaf\xb7\xe6\xb1\x82\xe7\x96\x91\xe4\xbc\xbc\xe6\x94\xbb\xe5\x87\xbb\xe8\xa1\x8c\xe4\xb8\xba\xef\xbc\x81";document.getElementById("b").innerHTML = "\xe5\xa6\x82\xe6\x9e\x9c\xe6\x82\xa8\xe6\x98\xaf\xe7\xab\x99\xe9\x95\xbf\xef\xbc\x8c\xe6\x82\xa8\xe5\x8f\xaf\xe4\xbb\xa5\xe5\x89\x8d\xe5\xbe\x80WAF\xe6\x8e\xa7\xe5\x88\xb6\xe5\x8f\xb0\xe8\xbf\x9b\xe8\xa1\x8c\xe8\xaf\xaf\xe6\x8a\xa5\xe5\xb1\x8f\xe8\x94\xbd\xe8\xae\xbe\xe7\xbd\xae\xef\xbc\x8c\xe8\xae\xa9\xe6\x82\xa8\xe7\x9a\x84\xe8\xae\xbf\xe9\x97\xae\xe4\xb8\x8d\xe5\x86\x8d\xe8\xa2\xab\xe6\x8b\xa6\xe6\x88\xaa";document.getElementById("c").innerHTML = "\xe4\xba\x8b\xe4\xbb\xb6ID\xef\xbc\x9a";}function changeLanguageEn() {document.getElementById("title").innerHTML = "The access is blocked.";document.getElementById("a").innerHTML = "Sorry, your request has been intercepted because it appears to be an attack.";document.getElementById("b").innerHTML = "If you are the webmaster, configure related parameters on the WAF console to allow your requests.";document.getElementById("c").innerHTML = "Event ID:";}var language = navigator.language || navigator.browserLanguage;var re_zh = /^zh/;if (language.match(re_zh)) {changeLanguageZh();document.getElementById("option-zh").setAttribute("selected", true);} else {changeLanguageEn();document.getElementById("option-en").setAttribute("selected", true);}</script>\n'

可以了
