### ISSUE TITLE
非常好用，就是大佬能不能让软件常驻后台。

### ISSUE THREAD

**Issue by EchoMinus** [6yy66yy/legod-auto-pause#3]
使用的时候因为个人习惯总是将软件×掉，大佬能不能添加一个设置为最小化到任务栏后台运行的功能？

**Comment by 6yy66yy** [comment]
更新了一个新的版本，能满足你的部分需求。
去掉了命令行，所有状态通过托盘和通知展示，你可以尝试一下
[新版本链接，无命令行](https://github.com/6yy66yy/legod-auto-pause/releases/tag/v2.1)

**Comment by EchoMinus** [comment]
感谢大佬
