### ISSUE TITLE
v2.1，win10系统，设置了雷神加速器path但打不开雷神，

### ISSUE THREAD

**Issue by superwx1985** [6yy66yy/legod-auto-pause#4]
设置好之后，右键任务栏小图标“打开雷神加速器”，只弹出了一个黑色的命令行窗口
![image](https://user-images.githubusercontent.com/9607255/200482645-dbf67ab3-c21b-457d-8709-c2956746c5fd.png)
![image](https://user-images.githubusercontent.com/9607255/200482879-bde2006a-fb01-40f8-b860-37fb58a91572.png)

**Comment by 6yy66yy** [comment]
去掉路径两边的双引号

**Comment by 6yy66yy** [comment]
> > 去掉路径两边的双引号
> 
> 好像不是引号的问题，os.system('start '+self.legod.lepath)，这里对路径含空格时会有错

是有这个问题，我一直是用的桌面快捷方式作为启动地址，所以没有问题。已修复，回头打包一版提一个release
