### ISSUE TITLE
[增强👾]加个关闭游戏后，延时暂停选项，很多时候只是重启一下游戏，很快就会重新运行游戏。

### ISSUE THREAD

**Issue by GB756980** [6yy66yy/legod-auto-pause#5]
**您的功能请求是否与问题有关？请描述。**
否

**描述一下你希望有的新功能**
加个关闭游戏后，延时暂停选项，很多时候只是重启一下游戏，很快就会重新运行游戏。

**Comment by 6yy66yy** [comment]
已经存在的功能，修改配置文件中的`looptime`可以限定游戏关闭后多少秒内切换（或者重启）游戏不会关闭。
```
# 允许游戏关闭的时间（在此时间内切换游戏不会关闭加速器）单位：秒
looptime = 1
```
如果`looptime=30`代表游戏程序关闭30秒内重启游戏不会暂停时长
后续会考虑弹窗提示和交互。

**Comment by GB756980** [comment]
感谢答复，明白了
