### ISSUE TITLE
怎样拿到暂停时间对应的接口的

### ISSUE THREAD

**Issue by JavaNee** [6yy66yy/legod-auto-pause#8]
老哥求教

**Comment by 6yy66yy** [comment]
官网抓包拿到的😶

**Comment by JavaNee** [comment]
哦哦看到官网有了，有抓过客户端吗

**Comment by 6yy66yy** [comment]
抓客户端的比较麻烦，而且有一定风险。如果想抓可以尝试wireshark，不过一般都是Https证书加密的，我之前在网上看到一种Hook ssl绕过Https加密的方式。具体可以查查，找不到链接了

**Comment by JavaNee** [comment]
好的谢了老哥
