### ISSUE TITLE
[增强👾]

### ISSUE THREAD

**Issue by baozihaochima** [6yy66yy/legod-auto-pause#9]
感觉可以加一个开机启动的设置

**Comment by 6yy66yy** [comment]
请看这里，如果想的话可以自行设置[如何设置为开机自启](https://github.com/6yy66yy/legod-auto-pause/wiki/%E4%B8%80%E4%BA%9B%E5%B8%B8%E8%A7%81%E7%96%91%E9%97%AE%E5%8F%8A%E8%A7%A3%E7%AD%94%EF%BC%88AI%E7%94%9F%E6%88%90%EF%BC%89#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E8%87%AA%E5%90%AF)
